### PR TITLE
[RFC] Transactions

### PR DESCRIPTION
**Pull request by andrewgregory**
Documentation and callback support are still missing, so this is not ready to be pulled yet.  An in-progress version of callback support is available on my callbacks branch, including a working example script to install/remove packages.  Note: the script uses my pacutils library for the config parsing: https://github.com/andrewgregory/pacutils (perl interface at: https://github.com/andrewgregory/perl-pacutils).

### CODE REVIEW

**Comment by juster** [comment]
I thought you might need transactions but I was hoping you would communicate with me more if you were going to make a major contribution. For implementing transactions the most difficult and tedious part is handling the error conditions and the callbacks. The other things are relatively straightforward.

Please look at the old design I used for transactions. I would prefer using an object to wrap transactions with methods for prepare, commit, release, etc:
https://github.com/juster/perl-alpm/blob/e848cdb5d4f0e762a26e5c514aead55ccf80f2c3/lib/ALPM/Transaction.pod

I don't agree with your implicit belief that every datum should be wrapped inside an object. Because perl is not entirely an object-oriented language and we are wrapping a library written in C which is even less-so, I prefer a simple and transparent form of data. For example, a file list is simply a list of file paths, which are strings. This is simple. Binary search is faster than a flat search but I would prefer empirical evidence like benchmarks to justify the added complexity. This is a bit radical but I ultimately think the added complexity should not be taken for granted as a necessity. The boilerplate classes are also not very helpful in that they add an extra level of indirection to do essentially the same thing.

For a more extreme example, if it were easily possible I would prefer retrieving packages as hashrefs instead of objects. Packages are entries in a database, they have no mutators, and are part of no inheritence scheme so making them objects is rather unnecessary. libalpm seems to encourage accessors and mutators in their design which makes it seem strangely Java influenced.

Regarding exceptions, I think I used to have an error class like that. A simpler solution might be to convert the error no into a string. Something like "$alpm->errsym();" to retrieve a string with a name similar to the C enum value entry. I'm not sure if the errno would ever need to be converted back the other way from a string/symbol to a number?

I need some time to ruminate on some of these but I'll work with you this weekend to add transactions.

**Comment by andrewgregory** [comment]
Using a transaction object makes little sense.  ALPM can only have one transaction at a time, so it would have to be a singleton anyway, and the callbacks are used outside of transactions, so it doesn't make sense to tie them to the transaction.

Exceptions need to be objects.  The transaction exceptions need to be able to return additional data somehow and hash members is the easiest way to do that.  Simple strings simply will not allow robust error handling in that case.  Blessing the hashes into appropriate packages will allow class-based exception handling while still having them stringify into something suitable for quick one-liners.

**Comment by juster** [comment]
The transaction object is to avoid cluttering the ALPM namespace. You can only create one for each handle. The object also makes releasing automatic when the reference goes out of scope. This is what ALPM objects already do.

The data that function like ...trans_prepare and ...trans_release store on error conditions can also be stored in the transaction object. Alternatively they can return undef on success and an arrayref on failure. Exceptions are not the only possible solution.

If you have a specific idea in mind why exceptions are needed, an example would be helpful. As a vague approach to robustness I don't think they're warranted. They just create a necessity for more boilerplate code.

**Comment by andrewgregory** [comment]
Exception objects are far more robust.  They scale well from simple scripts with no explicit error handling to full-fledged applications.  Just returning the raw error data from the functions will require more work by the users as they have to check the return value and manually generate a suitable message, whereas we can simply provide stringification for an object.  And returning undef on success is backwards from how errors are normally indicated in perl.  Attaching the data to a transaction object would also create a trap for the unwary:

``` perl
try {
    my $t = $alpm->trans;
    $t->add($pkg);
    $t->prepare;
    $t->commit;
} catch {
    # $t has gone out of scope, no exception information available.
};
```

**Comment by juster** [comment]
Returning undef on success is how most perl builtins work. If you replace undef with 0 it is how most of UNIX works. libalpm also returns 0 on success for most if not all functions. Requiring users to check return values is pesky but most of the ALPM module already operates in that fashion. In a way it is more straightforward and enforces error checking to be close to the calling code. There are many possibilities, for example:

```
my $t = $alpm->trans('flag1 flag2');
$t->add($_) for(@pkgs);
$t->prepare or die $t->strerror;
$t->commit or die $t->strerror;
undef $t;
```

I would consider your example to be a reason to not use exceptions; except where necessary. There isn't even a native try/catch syntax in perl. Instead there are clever hacks created by modules to accomodate the syntax. If this were Java it would be different. Perl is funky. I just need more than buzzwords to convince me of the necessity of Exceptions and a slew of classes. Something like specific examples or specific reasons, not vague marketing terms. I'm just not convinced.

**Comment by juster** [comment]
Since you'll be taking over maintainership this pull request is obsolete. Have fun!

**Pull request closed without merging**
